name: Makefile CI

on:
  push:
    branches: [ "Dev" ]
  pull_request:
    branches: [ "Dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Install dependencies
      run: make

