name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        run: sudo apt install -y cmake ninja-build

      - name: Install Dependencies
        run: |
          sudo apt install -y vulkan-tools libvulkan-dev vulkan-validationlayers-dev spirv-tools libglfw3-dev libglm-dev

      - name: Build Project
        run: |
          mkdir -p build
          cd build
          cmake -G Ninja ..
          ninja

      - name: Run Executable
        run: |
          cd build
          ./NeonEngine
